version: '3.3'
services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'production'
    networks:
      - backend
    ports:
      - "5431:5432"
    volumes:
      - database-pg:/var/lib/postgresql/data
networks:
  backend:
    driver: bridge
  hub_network:
    external: false

volumes:
  database-pg: